services:
    david63.pmmonitor.listener:
        class: david63\pmmonitor\event\listener
        arguments:
        tags:
            - { name: event.listener }

    david63.pmmonitor.admin.controller:
        class: david63\pmmonitor\controller\admin_controller
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@pagination'
            - '@user'
            - '@auth'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@language'			
